#!/bin/bash

#------------------------------------------------------------------------
# Set up Xgrid Controller user
#------------------------------------------------------------------------

dscl localhost -create /Local/Default/Groups/_xgridagent || true
dscl localhost -create /Local/Default/Groups/_xgridagent gid 86 || true
dscl localhost -create /Local/Default/Users/_xgridagent || true
dscl localhost -create /Local/Default/Users/_xgridagent uid 86 || true
dscl localhost -create /Local/Default/Users/_xgridagent gid 86 || true
dscl localhost -create /Local/Default/Users/_xgridagent shell /usr/bin/false || true
dscl localhost -create /Local/Default/Users/_xgridagent home /var/xgrid/agent || true
dscl localhost -create /Local/Default/Users/_xgridagent passwd "*" || true
dscl localhost -create /Local/Default/Users/_xgridagent RealName "Xgrid Agent" || true
dscl localhost -create /Local/Default/Users/_xgridagent RecordName xgridagent || true

exit 0
